"""
389. Find the Difference


Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.



"""

# hashmap time compexity O(n + m) space complextiy O(n)


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dicts = {}
        for ch in s:
            dicts[ch] = dicts.get(ch, 0) + 1
        for ch in t:
            if ch not in dicts:
                return ch
            elif dicts[ch] == 0:
                return ch
            else:
                dicts[ch] -= 1

# bit manipulation


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        res = 0
        for ch in s:
            res ^= ord(ch)
        for ch in t:
            res ^= ord(ch)
        return chr(res)

